metric: srs
formula: q2q2
mode: native_mode
models:
  native_embedder:
    name: Alibaba-NLP/gte-modernbert-base
    max_context_length: 8190
    prefix: ''
    pool_type: cls
datasets:
- path: uonlp/CulturaX
  split: train
  data_files: en/en_part_0000*.parquet
  text_column: text
  commit_hash: 6a8734bc69fefcbb7735f4f9250f43e4cd7a442e
probe_config:
  sequence_length:
    min: 8
    max: 8
  samples_per_length: 25
  token_per_sample: 500
  group_amount: 25
advanced:
  batch_size: 32
  device: cuda
seed: 42